### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by code-odbo** [pmcfarland/security_now_downloader#1]
![image](https://user-images.githubusercontent.com/23518263/134119281-10f9620c-f4cf-469d-9144-bbe8f3569389.png)

Thank you for creating this script! ;-)  It was working in Windows 10 before, but I'm using W10 21H1 and got the posted error.  Any ideas?

**Comment by pmcfarland** [comment]
Ah ok I see what's happening now. Steve has changed the html for his site and so my parsing of the webpage to find the latest episode number broke. I'll go ahead and shift it down a few lines. Thanks for letting me know.

**Comment by pmcfarland** [comment]
Yeah in the html for the page it used to be:

```
<!-- ################################################################################ -->



<a name="836"></a>
```

but somewhere along the way Steve added:

```
<!-- ################################################################################ -->

<!-- td style="color:#B00; font-size:7.5pt;"><em>This week's transcripts will be a few days delayed.</em></td -->
<!-- td style="color:#B00; font-size:7.5pt;"><em>This episode's transcript is underway.</em></td -->
<!-- <td><em>This episode's transcript is under way.</em></td> -->


<a name="836"></a>
```

so I have increased the offset to compensate

**Comment by code-odbo** [comment]
I'm not even at script-kitty level, so I'm grateful for smart people like you . . . thank you good sir!
